//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelTool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModelTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entering directory {0}....
        /// </summary>
        internal static string FileStateChangingDir {
            get {
                return ResourceManager.GetString("FileStateChangingDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import complete!.
        /// </summary>
        internal static string FileStateImportComplete {
            get {
                return ResourceManager.GetString("FileStateImportComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing {0}....
        /// </summary>
        internal static string FileStateImporting {
            get {
                return ResourceManager.GetString("FileStateImporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing loaded..
        /// </summary>
        internal static string FileStateNothingLoaded {
            get {
                return ResourceManager.GetString("FileStateNothingLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load complete!.
        /// </summary>
        internal static string FileStateReadComplete {
            get {
                return ResourceManager.GetString("FileStateReadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading {0}....
        /// </summary>
        internal static string FileStateReading {
            get {
                return ResourceManager.GetString("FileStateReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready..
        /// </summary>
        internal static string FileStateReady {
            get {
                return ResourceManager.GetString("FileStateReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save complete!.
        /// </summary>
        internal static string FileStateWriteComplete {
            get {
                return ResourceManager.GetString("FileStateWriteComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving {0}....
        /// </summary>
        internal static string FileStateWriting {
            get {
                return ResourceManager.GetString("FileStateWriting", resourceCulture);
            }
        }
    }
}
